### ISSUE TITLE
Not able to retrieve variable value or save the solution to external file

### ISSUE THREAD

**Issue by carlosnatalino** [IBMDecisionOptimization/doopl-examples#1]
Hi,

I have not been able to retrieve the values of variables back to the Python script. Moreover, although we have setExportExternalData and setExportInternalData, I could not find the method that exports the solution to an external file.

Is it possible to retrieve the value of a variable or export it to a file?

Best,

Carlos

**Comment by vlkong** [comment]
does this help ? https://www-01.ibm.com/support/docview.wss?uid=swg21508158

**Comment by carlosnatalino** [comment]
Hi @vlkong,

Thanks for the suggestion. Yes, it helped me to export the values to a file.

However, I still cannot retrieve the value of a variable in Python. Is there any way to do it?

For instance, I'm using the following code to load and solve a model.

```
with create_opl_model(model='./replicaplacement.mod', data=['./topology-rpp.dat', './problem-rpp.dat']) as opl:
    opl.run()
    print('objective=%s' % opl.objective_value) # Get the engine objective value
```

However, when I try to access any variable from the solution through `opl.report` or `opl.output_table_names`, these two lists/sets are empty.

Is there any way to retrieve the value of variables from the `opl` object?

Thanks!

**Comment by vlkong** [comment]
Hi @carlosnatalino 

I will need your .mod / .dat (or a minimal model that reproduce your issue) to help you.
For information, the following program works:
```
from doopl.factory import *

mod =  "C:/Program Files/IBM/ILOG/CPLEX_Studio129/opl/examples/opl/models/EconPlanning/econPlanning.mod"
dat =  "C:/Program Files/IBM/ILOG/CPLEX_Studio129/opl/examples/opl/models/EconPlanning/econPlanning.dat"
with create_opl_model(model=mod, data=dat) as opl :    
    status = opl.run()
    print("status =",status)
    print(opl.report)
    print("output map")
    print(opl.output_table_names)

```

(using COS 12.9 samples)

You can send me your model at viulong.kong@fr.ibm.com

**Comment by carlosnatalino** [comment]
Hi @vlkong,

Thanks a lot for your reply. I've shared with you a sample model that shows the issue I'm facing.

Apparently, the `opl` object only recovers the values of tuples, but not the values of integer or float variables.

Is there any way to recover the values of such variables?

Thanks!

**Comment by vlkong** [comment]
For the record, received data by email, answered:

```
Yes, you can only get tupleset as output in current version.
You can work around this by creating a tupleset containing the values you want as <name, value> pairs.
At the end of your .mod, add:

tuple OUTPUT {
        string Name;
        float Value;
}
{OUTPUT} output = {<"number_dcs", number_dcs>,
                   <"objective", objective>};
```

Thanks

**Comment by nicolasj92** [comment]
Hi, is it possible to do this with multidimensional variables?
I get an error when I have an array boolean decision variable that is e.g. of dimension 5x10.
I can use the solution that was suggested by @vlkong but only if I take a single value of the array (e.g. X[1][1]) but not the whole array.

**Comment by vberaudi** [comment]
With tupleSets comprehensions, you can export any OPL object from OPL to python.
This is the protocol that is used also with DO in Watson Studio / Cloud Pak for Data, where only tupleSet can be used in input or output.
For example, look at mulprod.mod example.
```
{string} Products = ...;
{string} Resources = ...;

dvar float+ Inside[Products][Periods];

...
...

tuple InsideSolutionT{ 
	string Products; 
	int Periods; 
	float value; 
};
{InsideSolutionT} InsideSolution = {<i0,i1,Inside[i0][i1]> | i0 in Products,i1 in Periods};

```
