### ISSUE TITLE
Accessing multidimensional outputs

### ISSUE THREAD

**Issue by nicolasj92** [IBMDecisionOptimization/doopl-examples#11]
Hi, is it possible to access the output / final values of multidimensional boolean decision variables?
I get an error when I have an array boolean decision variable that is e.g. of dimension 5x10.
I can use the solution that was suggested by @vlkong but only if I take a single value of the array (e.g. X[1][1]) but not the whole array.

Related to
https://github.com/IBMDecisionOptimization/doopl-examples/issues/1

**Comment by vberaudi** [comment]
With tupleSets comprehensions, you can export any OPL object from OPL to python.
This is the protocol that is used also with DO in Watson Studio / Cloud Pak for Data, where only tupleSet can be used in input or output.
For example, look at mulprod.mod example.
```
{string} Products = ...;
{string} Resources = ...;

dvar float+ Inside[Products][Periods];

...
...

tuple InsideSolutionT{ 
	string Products; 
	int Periods; 
	float value; 
};
{InsideSolutionT} InsideSolution = {<i0,i1,Inside[i0][i1]> | i0 in Products,i1 in Periods};
```
