### ISSUE TITLE
OPL finds a solution, but doopl does not retrieve anyting

### ISSUE THREAD

**Issue by tdubsound** [IBMDecisionOptimization/doopl-examples#3]
I have a model where I am able to generate a valid .dat file and I run it and retrieve a tuple set. I can run this in CPLEX studio, and I can run this by calling oplf.create_opl_model and supplying the mod and dat files. However, when I populate the model using the dataframes, I run into some problems. Specifically, the results tuple set I create is empty (it prints  "{}"), but using the other methods I get a non-empty set. Right now, my workaround is to call the model a second time but feed it my dat file.

**Comment by vlkong** [comment]
Can you please send me your code ? You can send it to my mailbox viulong.kong@fr.ibm.com 
Thanks

**Comment by vlkong** [comment]
Old issue, no news - closing.

**Comment by mehdi2019gaied** [comment]
HI,

I have an opl model and i wanna run it with python but I got this exception:

   return _opl.IloEnv__createOplModel(self, modelSource)

IloException

can u help me ?

Best regards

my code is :from doopl.factory import *
import os
from os.path import dirname, abspath, join
DATADIR=join(dirname(abspath(__file__)),'data')
mod=join(DATADIR,"test.mod")
dat=join(DATADIR,"test.dat")
gen_dir=os.path.join(DATADIR,"generated")

if not os.path.isdir(gen_dir):
       os.makedirs(gen_dir)
 

# Create an OPL model from a .mod file
with create_opl_model(model=mod, data=dat) as opl:
    # tuple can be a list of tuples, a pandas dataframe...
    #opl.set_input("TupleSet1", tuples)

    # Generate the problem and solve it.
    opl.run()
   
    print(opl)
    print(opl.objective_value)
    print(opl.get_table("InVolumeThroughHubonTestRes"))
    print(opl.get_table("OutVolumeThroughHubonTestRes"))
    print(opl.report)
