### ISSUE TITLE
Cannot Import doopl 

### ISSUE THREAD

**Issue by ghost** [IBMDecisionOptimization/doopl-examples#4]
Hi, there! 

I try on my machine and my colleague's as well. 
We have the same error. 

> from . import _opl
> ImportError: DLL load failed: The specified module could not be found.

Right now, we have CPLEX 12.10, python 3.7.4. 
We use pip install doopl to install the package. 

Previously under CPLEX 12.9, I can run the example codes, without any error. 

Thanks!

Yang

**Comment by vlkong** [comment]
Hi Yang,

doopl does not support cplex 12.10 yet. I will publish a new version as soon as possible.

Thanks

**Comment by ghost** [comment]
Thanks for the quick reply!

As always, best regards!

**Comment by vlkong** [comment]
doopl with support for cplex 12.10 has been deployed on pypi. Can you please try again ?

Thanks

**Comment by ghost** [comment]
It works perfectly!

Thanks!

**Comment by BedirhanSARIMEHMET** [comment]
Hi @vlkong ! I get the following error:
ImportError: Could not import OPL wrappers. Make sure than OPL bin directory is in the PATH
They appear to exist in Path, but I still get errors.
Can you help me?
ILOG: 12.6.2
PYTHON: 3.6.8
